version: '4.0'
services:
  nest-api:
    container_name: itpsruapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    depends_on:
      - postgres
    env_file:
      - .env
