service:
  name: itpsruplus-backend

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  environment:

functions:
  main:
    handler: dist/src/serverless.handler
    events:
      - http:
          method: any
          path:
package:
  exclude:
    - node_modules/**
    - venv/**
